volumes:
  open-webui:
  librechat-data:
  mongodb-data:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

  librechat:
    image: ghcr.io/danny-avila/librechat:latest
    container_name: librechat
    restart: unless-stopped
    ports:
      - "3080:3080"
    volumes:
      - librechat-data:/app/api/data
      - ./librechat.yaml:/workspaces/local-ai-packaged/librechat.yaml
    env_file:
      - .env.librechat
    depends_on:
      - mongodb
